### ISSUE TITLE
What compatibility are we testing?

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/sbt-compatibility#28]
I am not sure if `compatibilityReportDependencyIssues` or `compatibilityCheck ` completely describes what this plugin aims to do. To me compatibility sounds like if a transitive library X is still compatible with the rest of my dependency graph.

If we are mostly enforcing some version scheme compliance like SemVer, maybe naming it as `versionPolicyCheck` + `versionPolicyDependencyCheck` might reflect what's going on?

**Comment by eed3si9n** [comment]
Another idea for prefix might be `versioning`, like `versioningCheck`, `versioningDependencyRules`, etc.

**Comment by eed3si9n** [comment]
@julienrf so is it ok to rename to sbt-version-policy all around?

**Comment by julienrf** [comment]
Yes.
